language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-24
before_install:
  - chmod +x ./gradlew
script:
  - ./gradlew  assembleRelease
branches:
  only:
    - master
